name: Publish PyPI

on:
  push:
    branches:
      - master

# Limit GITHUB_TOKEN permissions
permissions:
  contents: read

jobs:
  build:
    environment: pypi-release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Change image paths in README
        run: |
          sed -i 's|(./docs/assets/|(https://raw.githubusercontent.com/fwkrumm/shmlock/master/docs/assets/|g' README.md

      - name: Build package
        run: python -m build

      - name: Publish to PyPI
        run: |
          twine upload dist/* || { echo "::error:: ❌ Error: Upload failed. Possibly because the version already exists."; exit 1; }
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN_ENV }}
