name: Weekly Latest Python Check

on:
  push:  # temporary: remove after testing
  workflow_dispatch:  # allows manual triggering from the Actions tab (any branch)
  schedule:
    - cron: '0 12 * * 1' # Every Monday at 12:00 UTC

# Limit GITHUB_TOKEN permissions
permissions:
  contents: read

jobs:
  Unittests:
    # run unit tests against the most recent Python version available
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest, ubuntu-22.04-arm, ubuntu-24.04-arm]
    steps:
      - uses: actions/checkout@v6
      - name: Set up latest Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-optional.txt
      - name: Run Tests from local files
        run: |
          python -m coverage run -m unittest discover
          coverage report -m

  Examples:
    # run examples from ./examples folder against the most recent Python version available
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest, ubuntu-22.04-arm, ubuntu-24.04-arm]
    steps:
      - uses: actions/checkout@v6
      - name: Set up latest Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'
      - name: Upgrade pip
        run: pip install --upgrade pip
      - name: Install Windows-specific requirements
        if: runner.os == 'Windows'
        run: |
          pip install -r requirements_win.txt
      - name: Install shmlock and dependencies
        run: |
          pip install . -r requirements.txt
          pip install -r requirements-optional.txt
      - name: Run Examples from installed package
        run: |
          python ./examples/performance_analysis/run_perf.py
          python ./examples/performance_analysis/run_poll_perf.py

  Pylint:
    # run pylint against the most recent Python version available
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up latest Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-optional.txt
      - name: Run pylint
        run: |
          pylint --rcfile=.pylintrc tests
          pylint --rcfile=.pylintrc shmlock
          pylint --rcfile=.pylintrc examples
